version: "3.9"
services:
  selenium:
    image: "selenium/standalone-firefox"
    deploy:
      resources:
        limits:
          cpus: 0.2
          memory: 256M
    environment:
      VNC_NO_PASSWORD: 1
      SE_NODE_SESSION_TIMEOUT: 999999999
    #ports:             # Access in browser at ip:4444, only use briefly for troubleshooting.
    # - "4444:4444"     # NOT AUTHENTICATED, anyone can access/control your Instagram if this is enabled.
    shm_size: 2gb
    healthcheck:
      test: ["CMD", "/opt/bin/check-grid.sh", "--host", "0.0.0.0", "--port", "4444"]
      interval: 10s
      timeout: 5s
      retries: 3
  linkedin-headline:
    build: .
    deploy:
      resources:
        limits:
          cpus: 0.2
          memory: 256M
    links:
      - "selenium:selenium"
    depends_on:
      selenium:
        condition: "service_healthy"
